### ISSUE TITLE
"Fair Play!" Award Broken at End of Matches

### ISSUE THREAD

**Issue by joefil1991** [TeamForbiddenLLC/warfork-qfusion#146]
When you do a "good game" Vsay at the end of a match, the "Fair Play!" award isn't displayed above the scoreboard like it is in Warsow, even though the server log shows the award was received:

```
joefil1991 receives a 'Fair Play!' award.
^2joefil1991^2: (v) Good game!
S4WDU5T receives a 'Fair Play!' award.
S4WDU5T^2: (v) Good game!
```

**Comment by Warfork** [comment]
Fixed and closed the issue.
