### ISSUE TITLE
Player Trail Colors - Use int instead of float

### ISSUE THREAD

**Issue by Gelmo** [TeamForbiddenLLC/warfork-qfusion#190]
https://github.com/TeamForbiddenLLC/warfork-qfusion/blob/1bc009543f221d3fc4f790308bece33d1a6c2ebd/source/cgame/cg_effects.cpp#L558

Rather than floats from 0-1, shouldn't this be ints from 0-255 like other color options available to the player?

**Comment by learn-more** [comment]
This makes sense.
The clamping should also be fixed, because now it is clamped twice. Once manually, and once with clamp.

**Comment by learn-more** [comment]
This should be fixed now
