### ISSUE TITLE
XPM icon doesn't load on linux

### ISSUE THREAD

**Issue by Warfork** [TeamForbiddenLLC/warfork-qfusion#220]
The Warfork XPM icon (located at https://github.com/TeamForbiddenLLC/warfork-qfusion/tree/master/icons) is no longer appearing in my taskbar on Ubuntu 22.04.03 LTS with Mate Desktop when I compile Warfork. This issue persists with any XPM icon, such as those for Warfork, Warsow, Qfusion, etc. The problem also occurs in the current release available on Steam. Interestingly, using an older release (build 4269802) from October 08, 2019, which I have stored in my archives, displays the icon. However, if I build the exact same commit, the icon does not appear.

![icon_1](https://github.com/TeamForbiddenLLC/warfork-qfusion/assets/51063252/c8b25273-11b9-4476-99ce-389db22028ee)

**Comment by Warfork** [comment]
I forgot to mention I launched Warsow 2.1 and the icon appears.

**Comment by Gelmo** [comment]
@Warfork See if this is resolved by installing libxpm-dev and rebuilding

**Comment by Warfork** [comment]
@Gelmo Still the same.

**Comment by Warfork** [comment]
This has been resolved and is a non-issue.
