### ISSUE TITLE
Start game button not working

### ISSUE THREAD

**Issue by bakomox** [TeamForbiddenLLC/warfork-qfusion#245]
hi i got a problem with the latest update 2.13 when i click "start game" button nothing happens and no errors too

im on windows 10 iot ltsc 2021 and my specs are ryzen 4350g APU, 32GB ddr4 ram, 1tb ssd

![Screenshot (1)](https://github.com/TeamForbiddenLLC/warfork-qfusion/assets/12554635/1c2fd62e-cf63-489f-afb5-db11e28d1172)

**Comment by Warfork** [comment]
Seems to be happening for me too on Ubuntu. I'll look into it thanks. For the time being you can start a server by opening console and typing g_gametype "ca" for example and map wfdm2.

**Comment by Warfork** [comment]
@bakomox @CoolElectronics it works fine for me on windows, but not ubuntu.

**Comment by CoolElectronics** [comment]
works for me on arch linux

**Comment by Warfork** [comment]
> > @bakomox @CoolElectronics it works fine for me on windows, but not ubuntu.
> 
> i somewhat solve it or the button works by hovering the mouse outside the text but still inside the button area like this in the screenshot so ye this way i can play again
> 
> ![Screenshot (3)](https://private-user-images.githubusercontent.com/12554635/286827604-784ee605-4e4e-4d41-8ce2-55c14ead835d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjQ5NzgsIm5iZiI6MTcwMTMyNDY3OCwicGF0aCI6Ii8xMjU1NDYzNS8yODY4Mjc2MDQtNzg0ZWU2MDUtNGU0ZS00ZDQxLThjZTItNTVjMTRlYWQ4MzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA2MTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OGJhMjIxMzc4MTRhZGExZjNhMGNjYWY2N2RiOTY3ZDVlYTE0N2QzMGQ3MTRhOWM3Yzc2ZjY5ODlkMWNhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OCkdsg5SGOC_2YrQWGK24tQBjWD9yyQgffMgYAsJYcE)

I'll have to do more testing tomorrow. We haven't been able to figure out what's going on yet.

**Comment by Warfork** [comment]
@bakomox this was fixed by Gauley123 and will be in the next update
