### ISSUE TITLE
Some users can no longer launch the game directly from Steam

### ISSUE THREAD

**Issue by Warfork** [TeamForbiddenLLC/warfork-qfusion#248]
Some users can no longer launch the game directly from Steam, but can launch the executable.

carss — Yesterday at 5:59 PM
did something change with the game
[5:59 PM]
It wont launch anymore for me

carss — Yesterday at 6:07 PM
so any idea why does today warfork does not launch @Caine
[6:08 PM]
Nah it's like I click launch it goes to running
[6:08 PM]
then just go back to play

jAck — Yesterday at 12:48 PM
Hello, can someone help me ? The game is not opening since the update of today

@jAck
Hello, can someone help me ? The game is not opening since the update of today

Caine — Yesterday at 12:48 PM
what error message?

jAck — Yesterday at 12:48 PM
no error message at all

Caine — Yesterday at 12:48 PM
os?

jAck — Yesterday at 12:48 PM
I launch through Steam and it doesn't launch
[12:48 PM]
Windows 11 i think gonna check
[12:50 PM]
windows 10 sorry
[12:52 PM]
I have already uninstalled & reinstalled but still doesn't launch :/

schlafen  10 hours ago  
    
Can't use custom sounds anymore? Game just closes after start

**Comment by klaufir216** [comment]
People, please don't use my old version of soundmod with WF 2.13; its not compatible, it will just break your game. If you already have installed it, you can fix your warfork installation by either:

- uninstall & reinstall Warfork in Steam 
- or in Steam: 
  1. Right click on _**Warfork**_, 
  2. Select **_Properties..._**, 
  3. Select **_Installed files_**
  4. Select **_Verify integrity of game files_**.
