### ISSUE TITLE
Delimiter varies by steam command

### ISSUE THREAD

**Issue by Warfork** [TeamForbiddenLLC/warfork-qfusion#337]
Delimiter varies by Steam command:

g_permanent_operators uses <steamid64,steamid64,steamid64>
sv_whitelist uses <steamid64|steamid64|steamid64>
The delimiter should be consistent and use commas everywhere.

**Comment by CoolElectronics** [comment]
db37b8675bab002cf161e7bc0df77e4f56b0db38
