### ISSUE TITLE
 "coyote wins" always shows up when i frag a bot but the match is not over yet

### ISSUE THREAD

**Issue by bakomox** [TeamForbiddenLLC/warfork-qfusion#357]
instagib match with bots the map is jewels

![2](https://github.com/TeamForbiddenLLC/warfork-qfusion/assets/12554635/3807d144-a5ed-49c7-940f-65c6951add74)

**Comment by Gelmo** [comment]
The "Coyote wins" message is unrelated to the round state. You get that message when you kill someone that's moving above a certain speed. And the "Meep Meep" message is when you kill someone while you're moving above a certain speed.
