### ISSUE TITLE
team colored gap in gametypes without teams

### ISSUE THREAD

**Issue by haha-goodone-lol** [TeamForbiddenLLC/warfork-qfusion#363]
gap in playerlist is team colored, but this also happens when the gametype isn't a team based gametype
![image](https://github.com/TeamForbiddenLLC/warfork-qfusion/assets/34005548/2609b307-299c-49fa-98ef-feb291e03235)

**Comment by velzie** [comment]
cannot reproduce

**Comment by haha-goodone-lol** [comment]
do you have `cg_teamPLAYERScolorForce 1`?
