### ISSUE TITLE
Scan for content in Steam Workshop folders

### ISSUE THREAD

**Issue by Warfork** [TeamForbiddenLLC/warfork-qfusion#45]
The Steam Workshop (https://steamcommunity.com/workshop/) allows people to create, discover, and download content for their game. A live example can be found here for the game Counter-Strike Global Offensive: https://steamcommunity.com/app/730/workshop/

When the Steam user subscribes to content it is downloaded in one of the following paths based on their operating system (please confirm this is actually correct):

- [Windows 64bit] C:\Program Files (x86)\Steam\SteamApps\workshop\content\appid\
- [Windows 32bit] C:\Program Files\Steam\SteamApps\workshop\content\appid\
- [macOS] /Users/<username>/Library/Application Support/Steam/SteamApps/workshop/content/appid/
- [GNU/Linux] /home/<username>/.steam/steam/steamapps/workshop/content/appid

Each workshop item is downloaded in its own subfolder based on the assigned item id by steam (ie: /content/appid/1337 /content/appid/4343) containing whatever the content creator uploaded.

We need Warfork to add these directories. The cheapest and dirtiest way to get it to work appears to be to calling FS_AddBasePath for each subdirectory (with the correct appid). 

Potential Issues:

- Steam Client\Workshop Content and Warfork might be installed in another location\drive letter.
- What happens if it fails? ie: non-steam users.
- This would take care of clients, but what about servers? I guess for now it beats nothing if there's no solution.

Notes: 

- Mike recommended to iterate over folders with qfusion findfirst/findnext.
- This is a band-aid implementation until things are clearer with Microsoft/ID Software.
- The Warfork appid is 671610
- https://partner.steamgames.com/doc/features/workshop/implementation
- Intended uses: Gametype Scripts, Server Configs, Maps, Music, Sounds, Demos, etc. Nothing should change, just it also loads Steam workshop folders containing content.

**Comment by learn-more** [comment]
`FS_AddBasePath` Wont work here, because the game appends `basewf` to that directory, and that is not how steam stores the files.

**Comment by Warfork** [comment]
> @Warfork is this implemented with the new steamshim?

@learn-more I wasn't sure if I should edit the original issue or just create a new one specifically for Steam SDK because it talks about "We need Warfork to add these directories. The cheapest and dirtiest way to get it to work appears to be to calling FS_AddBasePath for each subdirectory (with the correct appid)." Let me know what is standard practice.
