### ISSUE TITLE
Sounds shouldn't be pure-checked

### ISSUE THREAD

**Issue by Warfork** [TeamForbiddenLLC/warfork-qfusion#70]
@bonkmaykr#0001 suggested that sounds shouldn't be pure-checked.

> Sounds aren't easy to cheat with and provide prettymuch no competitive advantage, so I feel that sound mods should all be allowed.
> 
> EDIT: I read GelmoSan's feedback and have changed my mind, I think that the hitsound, killsound, announcer etc could all not be pure-checked and then the actual map sounds will be pure checked, so that people do not use tricks such as power up timers.

**Comment by bonkmaykrQ** [comment]
Hey, I have an actual account here if you want to tag that: @bonkmaykrQ
